title: Fromm Komm
author: 0xfab1
description: Dies ist ein Blog bei dem Herr Fromm Kommentiert, kurz FrommKomm.

remote_theme: riggraz/no-style-please

theme_config:
  appearance: "light" # can be "light", "dark" or "auto"
  back_home_text: "<-- zurÃ¼ck" # customize text for homepage link in post layout
  date_format: "%Y-%m-%d" # customize how date is formatted
  show_description: true # show blog description in home page

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-gist
  - jekyll-sitemap
  - jemoji
  - rouge
